name: C/C++ CI

on: [push, pull_request]

# push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
            python-version: '3.7'
      - name: dependencies
        run: |
            sudo apt update -qq
            sudo apt install swig libboost-dev libarmadillo9 libarmadillo-dev cmake python3-setuptools python3-numpy python3-pip lcov
      - name: configure
        run: mkdir build && cd build && cmake -DBUILD_R=no -DCMAKE_BUILD_TYPE=DEBUG -DENABLE_TESTS=ON ..
      - name: build
        run: cd build && VERBOSE=1 make package-python
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.4.0
        env:
            CIBW_BEFORE_BUILD="pip install numpy==1.17.3 setuptools"
        with:
            package-dir: build/swig/python-packaging
        # to supply options, put them in 'env', like:
        # env:
        #   CIBW_SOME_OPTION: value

        #- uses: actions/upload-artifact@v2
        #with:
        #path: ./wheelhouse/*.whl
